metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.10.205.100, mac: 'b8:ae:ed:eb:62:43', disk: sda, network_interface: eno1}
        metal1: {ansible_host: 10.10.205.101, mac: 'b8:ae:ed:eb:61:33', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 10.10.205.102, mac: 'b8:ae:ed:eb:61:8d', disk: sda, network_interface: eno1}
    workers:
      hosts:
        metal3: {ansible_host: 10.10.205.103, mac: 'b8:ae:ed:eb:61:9f', disk: sda, network_interface: eno1}
